// proto语法版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.0
// source: leo.proto

// proto包名 如果别的proto文件需要引用本包 则需要通过leo.User的形式访问

package leo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommnetType int32

const (
	CommnetType_UNKNOWN CommnetType = 0
	CommnetType_STARTED CommnetType = 1
	CommnetType_RUNNING CommnetType = 2
)

// Enum value maps for CommnetType.
var (
	CommnetType_name = map[int32]string{
		0: "UNKNOWN",
		1: "STARTED",
		2: "RUNNING",
	}
	CommnetType_value = map[string]int32{
		"UNKNOWN": 0,
		"STARTED": 1,
		"RUNNING": 2,
	}
)

func (x CommnetType) Enum() *CommnetType {
	p := new(CommnetType)
	*p = x
	return p
}

func (x CommnetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommnetType) Descriptor() protoreflect.EnumDescriptor {
	return file_leo_proto_enumTypes[0].Descriptor()
}

func (CommnetType) Type() protoreflect.EnumType {
	return &file_leo_proto_enumTypes[0]
}

func (x CommnetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommnetType.Descriptor instead.
func (CommnetType) EnumDescriptor() ([]byte, []int) {
	return file_leo_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Desc   []byte `protobuf:"bytes,3,opt,name=desc,proto3,oneof" json:"desc,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_leo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_leo_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetDesc() []byte {
	if x != nil {
		return x.Desc
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content []byte                `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type    CommnetType           `protobuf:"varint,4,opt,name=type,proto3,enum=leo.CommnetType" json:"type,omitempty"`
	IdList  []int64               `protobuf:"varint,5,rep,packed,name=id_list,json=idList,proto3" json:"id_list,omitempty"`
	User    *User                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Other   map[string]*anypb.Any `protobuf:"bytes,7,rep,name=other,proto3" json:"other,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are assignable to OptionTarget:
	//	*Comment_Targeta
	//	*Comment_Targetb
	OptionTarget isComment_OptionTarget `protobuf_oneof:"option_target"`
}

func (x *Comment) Reset() {
	*x = Comment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_leo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_leo_proto_rawDescGZIP(), []int{1}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Comment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Comment) GetType() CommnetType {
	if x != nil {
		return x.Type
	}
	return CommnetType_UNKNOWN
}

func (x *Comment) GetIdList() []int64 {
	if x != nil {
		return x.IdList
	}
	return nil
}

func (x *Comment) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetOther() map[string]*anypb.Any {
	if x != nil {
		return x.Other
	}
	return nil
}

func (m *Comment) GetOptionTarget() isComment_OptionTarget {
	if m != nil {
		return m.OptionTarget
	}
	return nil
}

func (x *Comment) GetTargeta() string {
	if x, ok := x.GetOptionTarget().(*Comment_Targeta); ok {
		return x.Targeta
	}
	return ""
}

func (x *Comment) GetTargetb() []byte {
	if x, ok := x.GetOptionTarget().(*Comment_Targetb); ok {
		return x.Targetb
	}
	return nil
}

type isComment_OptionTarget interface {
	isComment_OptionTarget()
}

type Comment_Targeta struct {
	Targeta string `protobuf:"bytes,8,opt,name=targeta,proto3,oneof"`
}

type Comment_Targetb struct {
	Targetb []byte `protobuf:"bytes,9,opt,name=targetb,proto3,oneof"`
}

func (*Comment_Targeta) isComment_OptionTarget() {}

func (*Comment_Targetb) isComment_OptionTarget() {}

var File_leo_proto protoreflect.FileDescriptor

var file_leo_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6c, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6c, 0x65, 0x6f,
	0x1a, 0x10, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x51, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x64, 0x65, 0x73, 0x63, 0x22, 0xef, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x6c, 0x65, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6e, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x6c, 0x65, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x2d, 0x0a, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6c, 0x65, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x07, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x62, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x62, 0x1a, 0x4e, 0x0a, 0x0a, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x2a, 0x34, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x6e,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x32, 0x30, 0x0a,
	0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x09, 0x2e, 0x6c, 0x65, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x1a,
	0x0c, 0x2e, 0x6c, 0x65, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x42,
	0x10, 0x5a, 0x0e, 0x6c, 0x65, 0x65, 0x6b, 0x62, 0x6f, 0x78, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x65,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_leo_proto_rawDescOnce sync.Once
	file_leo_proto_rawDescData = file_leo_proto_rawDesc
)

func file_leo_proto_rawDescGZIP() []byte {
	file_leo_proto_rawDescOnce.Do(func() {
		file_leo_proto_rawDescData = protoimpl.X.CompressGZIP(file_leo_proto_rawDescData)
	})
	return file_leo_proto_rawDescData
}

var file_leo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_leo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_leo_proto_goTypes = []interface{}{
	(CommnetType)(0),  // 0: leo.CommnetType
	(*User)(nil),      // 1: leo.User
	(*Comment)(nil),   // 2: leo.Comment
	nil,               // 3: leo.Comment.OtherEntry
	(*anypb.Any)(nil), // 4: google.protobuf.Any
}
var file_leo_proto_depIdxs = []int32{
	0, // 0: leo.Comment.type:type_name -> leo.CommnetType
	1, // 1: leo.Comment.user:type_name -> leo.User
	3, // 2: leo.Comment.other:type_name -> leo.Comment.OtherEntry
	4, // 3: leo.Comment.OtherEntry.value:type_name -> google.protobuf.Any
	1, // 4: leo.Greeter.SayHello:input_type -> leo.User
	2, // 5: leo.Greeter.SayHello:output_type -> leo.Comment
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_leo_proto_init() }
func file_leo_proto_init() {
	if File_leo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_leo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_leo_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_leo_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Comment_Targeta)(nil),
		(*Comment_Targetb)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_leo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leo_proto_goTypes,
		DependencyIndexes: file_leo_proto_depIdxs,
		EnumInfos:         file_leo_proto_enumTypes,
		MessageInfos:      file_leo_proto_msgTypes,
	}.Build()
	File_leo_proto = out.File
	file_leo_proto_rawDesc = nil
	file_leo_proto_goTypes = nil
	file_leo_proto_depIdxs = nil
}
