version: '3'
services:
  nsqlookupd:
    container_name: nsqlookupd
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - '4161:4161'
      - '4160:4160'

  nsqd:
    container_name: nsqd
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=192.168.1.3:4160 -broadcast-address=192.168.1.3
    depends_on:
      - nsqlookupd
    ports:
      - '4151:4151'
      - '4150:4150'

  nsqadmin:
    container_name: nsqadmin
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=192.168.1.3:4161
    depends_on:
      - nsqlookupd
    ports:
      - '4171:4171'
